esphome:
  name: pyramid-touch-demo

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

external_components:
  - source: local

i2c:
  sda: 38
  scl: 39
  scan: true

logger:
  level: DEBUG

api:
ota:
wifi:
  ssid: "<YOUR_WIFI_SSID>"
  password: "<YOUR_WIFI_PASSWORD>"
  ap:
    ssid: "pyramid-touch-demo"
    password: "12345678"

# PyramidTouch: read STM32 touch and expose sensors
sensor:
  - platform: pyramidtouch
    address: 0x1A
    update_interval: 50ms
    publish_swipe_event: true
    swipe_timeout_ms: 500
    touch1:
      name: "Touch 1"
    touch2:
      name: "Touch 2"
    touch3:
      name: "Touch 3"
    touch4:
      name: "Touch 4"
    swipe_event:
      name: "Touch Swipe Event"
      entity_category: diagnostic

# In Home Assistant you can automate on:
# - Touch X == 1 to toggle lights
# - Swipe event values: 1=LEFT_UP, 2=LEFT_DOWN, 3=RIGHT_UP, 4=RIGHT_DOWN