esphome:
  name: switchc6_sender
  platform: ESP32
  board: esp32dev

# Load local custom components (espnow and espnow_switch_c6) from parent folder
external_components:
  - source: local
    path: ..

# Keep it simple: run ESPNOW-only and fix channel explicitly
logger:
  level: DEBUG

# No Wi-Fi configured → espnow requires an explicit channel
espnow:
  id: espnow1
  channel: 1
  auto_add_peer: true
  peers:
    - FF:FF:FF:FF:FF:FF
  on_receive:
    - lambda: |-
        // Log inbound data as a string
        std::string s(reinterpret_cast<const char *>(data), size);
        ESP_LOGI("espnow", "recv from %02X:%02X:%02X:%02X:%02X:%02X size=%u data=%s",
                 info.src_addr[0], info.src_addr[1], info.src_addr[2],
                 info.src_addr[3], info.src_addr[4], info.src_addr[5],
                 size, s.c_str());
  on_broadcast:
    - lambda: |-
        std::string s(reinterpret_cast<const char *>(data), size);
        ESP_LOGI("espnow", "broadcast size=%u data=%s", size, s.c_str());

# Replace MAC_HYPHEN with your target short MAC in XXXX-XXXX-XXXX format
# Update ch= to match espnow.channel above
switch:
  - platform: espnow_switch_c6
    name: "SwitchC6"
    espnow_id: espnow1
    mac: "B43A-4581-EC70"   # target MAC from B4:3A:45:81:EC:70
    channel: 1
    optimistic: true
